name: KaratekCore
author: Karatek_HD
version: 0.2.3
main: com.karatek.core.main.Main
commands:
   test:
   chatclear:
   cc:
   kopf:
   broadcast:
   globalmute:
   kvanish:
   kv:
   sync:
   devinfo:
   server:
   rank:


